import os
import streamlit as st
from agno.media import Image as AgnoImage
from medical_agent import agent
from PIL import Image as PILImage

st.set_page_config(
    page_title="Ventilator Asynchrony Analysis",
    page_icon="🫁",
    layout="wide",
)
st.markdown("##### 🫁 built using [Agno](https://github.com/agno-agi/agno)")

def main():
    with st.sidebar:
        st.info(
            "This tool provides AI-powered analysis of ventilator waveforms using "
            "advanced computer vision to detect patient-ventilator asynchronies."
        )
        st.warning(
            "⚠DISCLAIMER: This tool is for educational and informational purposes only. "
            "All analyses should be reviewed by qualified critical care professionals. "
            "Do not make clinical decisions based solely on this analysis."
        )

    st.title("🫁 Ventilator Asynchrony Detection Agent")
    st.write("Upload ventilator waveform images for professional analysis")

    upload_container = st.container()
    image_container = st.container()
    analysis_container = st.container()

    with upload_container:
        uploaded_file = st.file_uploader(
            "Upload Waveform Image",
            type=["jpg", "jpeg", "png"],
            help="Supported formats: JPG, JPEG, PNG",
        )

    if uploaded_file is not None:
        with image_container:
            col1, col2, col3 = st.columns([1, 2, 1])
            with col2:
                pil_image = PILImage.open(uploaded_file)
                width, height = pil_image.size
                aspect_ratio = width / height
                new_width = 500
                new_height = int(new_width / aspect_ratio)
                resized_image = pil_image.resize((new_width, new_height))

                st.image(
                    resized_image,
                    caption="Uploaded Waveform Image",
                    use_container_width=True,
                )

                analyze_button = st.button(
                    "🔍 Analyze Waveform", type="primary", use_container_width=True
                )

                additional_info = st.text_area(
                    "Provide additional context (e.g., ventilator settings, patient condition)",
                    placeholder="Enter ventilator settings, mode, or other relevant information...",
                )

        with analysis_container:
            if analyze_button:
                image_path = "temp_waveform_image.png"
                resized_image.save(image_path, format="PNG")

                with st.spinner("🔄 Analyzing waveform... Please wait."):
                    try:
                        agno_image = AgnoImage(filepath=image_path)
                        prompt = (
                            f"Analyze these ventilator waveforms considering the following context: {additional_info}"
                            if additional_info
                            else "Analyze these ventilator waveforms and identify any asynchronies."
                        )
                        response = agent.run(
                            prompt,
                            images=[agno_image],
                        )
                        st.markdown("### 📋 Asynchrony Analysis Results")
                        st.markdown("---")
                        if hasattr(response, "content"):
                            st.markdown(response.content)
                        elif isinstance(response, str):
                            st.markdown(response)
                        elif isinstance(response, dict) and "content" in response:
                            st.markdown(response["content"])
                        else:
                            st.markdown(str(response))
                        st.markdown("---")
                        st.caption(
                            "Note: This analysis is generated by AI and should be reviewed by "
                            "a qualified critical care professional."
                        )

                    except Exception as e:
                        st.error(f"Analysis error: {str(e)}")
                        st.info(
                            "Please try again or contact support if the issue persists."
                        )
                        print(f"Detailed error: {e}")
                    finally:
                        if os.path.exists(image_path):
                            os.remove(image_path)
    else:
        st.info("👆 Please upload a ventilator waveform image to begin analysis")

if __name__ == "__main__":
    main()